### ISSUE TITLE
Not Printing

### ISSUE THREAD

**Issue by bionx** [mmilidoni/zbtprinter#1]
Hi;
Installed the plugin, followed the instructions including changing the printer MAC Address, but then nothing prints.

Tried to modify the code a bit to debug through GAPDebug as follows and the zbtprinter object is okay. But no success or failure alerts are coming!

Please assist.

```
    var zbtprinter;
    zbtprinter = cordova.plugins.zbtprinter;

    console.log('zbtprinter:');
    console.log(zbtprinter);


    zbtprinter.print("^XA^FO10,10^AFN,26,13^FDHello, World!^FS^XZ",
    function(success) { 
        alert("Print ok");
        console.log("print ok");

    }, function(fail) { 
        alert(fail); 
        console.log("print error");
    }
    );
```

**Comment by mmilidoni** [comment]
Had you pair printer and phone? 

Check if mac address is ok on platforms/android/src/android/it/zenitlab/cordova/plugins/zbtprinter/ZebraBluetoothPrinter.java

**Comment by bionx** [comment]
Thanks for your prompt response 
Yes I have done both things. 
MAC address is correct and was updated in the file specified.

I can see in the debug that the object is created. 

When calling the method,  the success and failure functions do not get invoked.

Can you share with me a working sample.

Thanks.

**Comment by mmilidoni** [comment]
Hi, 
I update java class to launch an exception (converted to fail callback) if connection with printer fails.

Can you try it?

**Comment by yuxiaojian01** [comment]
Hi, mmilidoni, your code works well on my android phone, thank you very much!
But there is a minor error when I install the plugin. This plugin will generate a package under src folder with a name of "android.it.zenitlab.cordova.plugins.zbtprinter" automatically, in fact the package name should be "it.zenitlab.cordova.plugins.zbtprinter". 
So I changed the package name and it worked (I cut the folder named "it" from android to folder named src, and delete the folder android). Maybe that's why Bionx met some problem when calling the method.
By the way, the ZPL II code you provide does not work. I tried "^XA^FO100,75^BCN,100,Y,N,N^FD>:JF123456^FS^XZ" instead, it worked.

**Comment by mmilidoni** [comment]
Thank you for suggest!
What software do you use? Cordova or Phonegap? Have you installed with the following command?

cordova plugin add https://github.com/mmilidoni/zbtprinter.git

**Comment by yuxiaojian01** [comment]
Thank you for your reply.
I used phonegap, and followed the steps and used the api on this website: http://docs.phonegap.com/en/edge/guide_cli_index.md.html#The%20Command-Line%20Interface

But I didn't see any difference between cordova and phonegap's documentation.

Yes, I added the plugin.

**Comment by Migueluis** [comment]
Ayuda no se como usar el plugin lo declaro en javascript per no se que declarar en html espero puedas ayudarme soy novato en esto
